### ISSUE TITLE
Problems with profile pages with '/in/' in URL

### ISSUE THREAD

**Issue by yaroslaff** [nubelaco/linkedin-api-python3-examples#3]
I configured proxycurl_people_profile_api_endpoint.py but getting this error: 
~~~
$ python proxycurl_people_profile_api_endpoint.py 
{'code': 400, 'description': 'LinkedIn URLs should be in the format of https://www.linkedin.com/<profile-id>', 'name': 'Bad Request'}
~~~

But all profiles I see, including my own profile has addresses like this: https://www.linkedin.com/in/williamhgates/  (with `/in/` in address). How can I get profile address in proper format, without `/in/`?

**Comment by C-Nubela** [comment]
Hello there!

You should include the /in/ with the profile. Can you provide all of the customization you've done to the script so far?

**Comment by yaroslaff** [comment]
Oops, sorry. My fault, there were mistake in my code, I called with full linked-in address, not just ID. 
now it's perfectly working. Thank you for answer, I reviewed code and  fixed it in a minute.
